### ISSUE TITLE
Error Creating Policies.

### ISSUE THREAD

**Issue by kanys5** [trevi-software/trevi-hr#29]
Error:
Odoo Server Error

Traceback (most recent call last):
  File "C:\odoo\comunity14\odoo\addons\base\models\ir_http.py", line 237, in _dispatch
    result = request.dispatch()
  File "C:\odoo\comunity14\odoo\http.py", line 684, in dispatch
    result = self._call_function(**self.params)
  File "C:\odoo\comunity14\odoo\http.py", line 360, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "C:\odoo\comunity14\odoo\service\model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "C:\odoo\comunity14\odoo\http.py", line 348, in checked_call
    result = self.endpoint(*a, **kw)
  File "C:\odoo\comunity14\odoo\http.py", line 913, in __call__
    return self.method(*args, **kw)
  File "C:\odoo\comunity14\odoo\http.py", line 532, in response_wrap
    response = f(*args, **kw)
  File "C:\odoo\comunity14\odoo\addons\web\controllers\main.py", line 1389, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "C:\odoo\comunity14\odoo\addons\web\controllers\main.py", line 1381, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "C:\odoo\comunity14\odoo\api.py", line 399, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "C:\odoo\comunity14\odoo\api.py", line 386, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "C:\odoo\comunity14\odoo\models.py", line 6267, in onchange
    snapshot1 = Snapshot(record, nametree)
  File "C:\odoo\comunity14\odoo\models.py", line 6058, in __init__
    self.fetch(name)
  File "C:\odoo\comunity14\odoo\models.py", line 6068, in fetch
    self[name] = record[name]
  File "C:\odoo\comunity14\odoo\models.py", line 5675, in __getitem__
    return self._fields[key].__get__(self, type(self))
  File "C:\odoo\comunity14\odoo\fields.py", line 969, in __get__
    self.recompute(record)
  File "C:\odoo\comunity14\odoo\fields.py", line 1155, in recompute
    self.compute_value(recs)
  File "C:\odoo\comunity14\odoo\fields.py", line 1177, in compute_value
    records._compute_field_value(self)
  File "C:\odoo\comunity14\odoo\models.py", line 4070, in _compute_field_value
    getattr(self, field.compute)()
  File "c:\odoo\comunity14\addons\trevi-hr\hr_benefit\models\benefit_policy.py", line 121, in _compute_amounts
    adv = rec.benefit_id.get_latest_advantage(dToday)
  File "c:\odoo\comunity14\addons\trevi-hr\hr_benefit\models\benefit.py", line 77, in get_latest_advantage
    return self._get_latest(dToday, "advantage")
  File "c:\odoo\comunity14\addons\trevi-hr\hr_benefit\models\benefit.py", line 47, in _get_latest
    self.ensure_one()
  File "C:\odoo\comunity14\odoo\models.py", line 5000, in ensure_one
    raise ValueError("Expected singleton: %s" % self)
Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\odoo\comunity14\odoo\http.py", line 640, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "C:\odoo\comunity14\odoo\http.py", line 316, in _handle_exception
    raise exception.with_traceback(None) from new_cause
ValueError: Expected singleton: hr.benefit()

**Comment by mtelahun** [comment]
Thank you for your report!
This should be fixed now, both in the repository and the Odoo App store.
