### ISSUE TITLE
TypeError: create() missing 1 required positional argument: 'vals'

### ISSUE THREAD

**Issue by lesdekock** [trevi-software/trevi-hr#70]
### After installing your module resource_schedule recieved the following upon hr contract creation:

Odoo Server Error
Traceback (most recent call last):
  File "******/odoo-server/odoo/addons/base/models/ir_http.py", line 237, in _dispatch
    result = request.dispatch()
  File "******/odoo-server/odoo/http.py", line 685, in dispatch
    result = self._call_function(**self.params)
  File "******/odoo-server/odoo/http.py", line 361, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "******/odoo-server/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "******/odoo-server/odoo/http.py", line 349, in checked_call
    result = self.endpoint(*a, **kw)
  File "******/odoo-server/odoo/http.py", line 914, in __call__
    return self.method(*args, **kw)
  File "******/odoo-server/odoo/http.py", line 533, in response_wrap
    response = f(*args, **kw)
  File "******/odoo-server/addons/web/controllers/main.py", line 1388, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "******/odoo-server/addons/web/controllers/main.py", line 1380, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "******/odoo-server/odoo/api.py", line 399, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "******/odoo-server/odoo/api.py", line 386, in _call_kw_multi
    result = method(recs, *args, **kwargs)
Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "******/odoo-server/odoo/http.py", line 641, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "******/odoo-server/odoo/http.py", line 317, in _handle_exception
    raise exception.with_traceback(None) from new_cause
TypeError: create() missing 1 required positional argument: 'vals'

### Resolved by adding @api.model in front of def create on line 21 of hr_contract.py.

**Comment by mtelahun** [comment]
Hi @lesdekock 
You are right there should be an @api.model there, but that alone shouldn't be causing it to fail. Usually, the error: `TypeError: create() missing 1 required positional argument: 'vals'` when calling
a class method happens when the class hasn't been instantiated properly. Is the hr.contract object not being instantiated using the usual method: `self.env["hr.contract"]` ?
Can you tell me a bit more about the circumstances in which this failure is being triggered?
Thanks.

**Comment by lesdekock** [comment]
Not mutch to add really. After module installed, navigate to HR, Emplyees, Contracts and create a contract using the standard Create button. I would presume that at that stage the hr.contract would be instantiated properly as that is Odoo core code initiating the creation process.
